name: Build, test, and deploy

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        ./fritz develop

    - name: Lint sources
      run: |
        ./fritz lint

    - name: Build docs
      run: |
        ./fritz doc

    - name: Install SSH Client 🔑
      if: github.ref == 'refs/heads/master'
      uses: webfactory/ssh-agent@v0.2.0
      with:
        ssh-private-key: ${{ secrets.CI_DEPLOY_KEY }}

    - name: Deploy docs
      if: github.ref == 'refs/heads/master'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        FOLDER: doc/_build/html
        REPOSITORY_NAME: fritz-marshal/doc
        BRANCH: master
        SINGLE_COMMIT: true
        SSH: true
