name: Integration testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          uv sync --inexact --group dev
          ./fritz develop

      - name: Set up configs
        run: |
          cp fritz.defaults.yaml fritz.yaml
          cp kowalski/docker-compose.fritz.defaults.yaml kowalski/docker-compose.yaml

      - name: Build and spin up
        run: |
          ./fritz build --init
          docker network create fritz_net
          ./fritz run
          docker network inspect fritz_net

      - name: Run integration tests
        run: |
          ./fritz test
